#数据库配置(改名为config.yaml后使用)
DataBase:
  username: "YourUserName"
  password: "YourPassword"
  host: "localhost"
  port: "3306"
  dbName: "YourDbName"
  timeout: "10s"

JWTConfig:
  refreshTokenKey: "YourRefreshTokenKey"

LogConfig:
  logPath: "YourLogPath"
  rotateTime: 1 #更新文件时间，以分钟计
  maxAge: 3 #最大记录时间，以分钟计

EmailConfig:
  emailAddress: "SenderEmailAddress"
  smtpServer: "YourSmtpServer"
  smtpPort: "YourSmtpPort"
  name: "YourUserName"
  password: "YourPassword"