#数据库配置(改名为config.yaml后使用)
DataBase:
  username: "YourUserName"
  password: "YourPassword"
  host: "localhost"
  port: "3306"
  dbName: "YourDbName"
  timeout: "10s"
  redisAddr: "YourRedisAddr"
  redisPassword: "YourRedisPassword"
  redisDB: 0 #0 is the default db

JWTConfig:
  refreshTokenKey: "YourRefreshTokenKey"

LogConfig:
  logPath: "YourLogPath"
  rotateTime: 1 #更新文件时间，以分钟计
  maxAge: 3 #最大记录时间，以分钟计

EmailConfig:
  emailAddress: "SenderEmailAddress"
  smtpServer: "YourSmtpServer"
  smtpPort: "YourSmtpPort"
  name: "YourUserName"
  password: "YourPassword"
  expirationSeconds: 300 #How long ultil login email expires
  subscriptionHour: 8 # When to send subscription(24 hours)